puts "The students of Villains Accademy"
puts "------------------------"
puts "Dr Hannibal Lecter"
puts "Darth Vader"
puts "Nurse Ratched"
puts "Micheal Corelone"
puts "Alex DeLarge"
puts "The Wicked Witch of the West"
puts "Terminator"
puts "Freddy Krueger"
puts "The Joker"
puts "Joffrey Baratheon"
puts "Norman Bates"